services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: ${TYPEORM_USERNAME}
      MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
volumes:
  mysql_data:
